name: UnluckyGUI
version: 1.0.0
main: com.belws.unluckygui.core.PluginMain
api-version: 1.16  # Updated for 1.16+ compatibility
commands:
  ul:
    description: Opens the main menu
    usage: /ul

  role:
    description: "Opens the role menu for a player"
    usage: "/role <player_name>"
