name: UnluckyGUI
version: 1.0.0
main: com.belws.unluckygui.core.PluginMain
api-version: 1.16
commands:
  ul:
    description: Opens the main menu
    usage: /ul

  open:
    description: "Opens the player options menu"
    usage: "/open <player_name>"
